baseURL = "https://www.tsmanikandan.com"
title = "Mani's super cool site"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage ="en"

paginate = 10
canonifyUrls = true

pygmentstyle = "manni"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Manikandan Sundararajan"
    info = "Mid/Backend Developer + Mechanical Keyboard nerd"
    description = "Mani's super cool site & blog"
    keywords = "blog,developer,personal"
    avatarurl = "/images/avatar.jpg"

    favicon_32 = "/images/favicon-mondrian-2.ico"
    favicon_16 = "/images/favicon-mondrian-2.ico"

    footercontent = "Made with ❤️ & ☕ in NYC"

    hidecredits = false
    hidecopyright = false

    commit = true

    rtl = false

    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/tsmanikandan/"
    [[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/itsrainingmani/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://linkedin.com/in/mtiruman/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 4
    url = "https://gitlab.com/manikandan_ts"
[[params.social]]
    name = "Dev.to"
    icon = "fab fa-dev fa-2x"
    weight = 5
    url = "https://dev.to/tsmanikandan"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 4
    url = "/contact/"